# Site settings
title: Miroslav Kuťák
description: Senior iOS Engineer
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mauricio Urraco
user_description: I'm a Software Engineer from the Czech Republic, always searching for the next challenge; no task is too scary nor too difficult.
user_title: Senior iOS Engineer
email: kutakmiroslav@gmail.com
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
linkedin_username: miroslavkutak
github_username:  kutakmir
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
