# Site settings
title: Miroslav Ku콘치k
description: Senior iOS Engineer
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Miroslav Ku콘치k
user_description: 11 years of professional iOS developer experience (iOS 4-16), 20+ AppStore apps, Czech Technical University graduate. Swift & Obj-C, SwiftUI & UIKit, iOS & WatchOS, native development only. Startups. Team lead. Down to earth. Mr. Fix it. Let's talk!
user_title: Senior iOS Engineer
# email: kutakmiroslav@gmail.com
# twitter_username: lorem_ipsum
# instagram_username: mauriciourraco7
# facebook_username: mauricio.urraco
# linkedin_username: miroslavkutak
# github_username:  kutakmir
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
